main: com.cavetale.election.ElectionPlugin

name: Election
version: 0.1
description: Election Plugin
api-version: 1.13

author: StarTux
website: https://github.com/StarTux/Election

depend: [Core, SQL]
softdepend: []

commands:

  election:
    aliases: [elect]
    description: Election Command
    permission: election.election
    usage: |-
      /elect - List
      /elect <name>
      /elect <name> vote <choice>
      /elect <name> up <choice>
      /elect <name> down <choice>
      /elect <name> warp <choice>

  electionadmin:
    aliases: []
    description: Admin Command
    permission: election.admin
    usage: |-
      /electionadmin

permissions:

  election.election:
    description: Use /election
    default: op

  election.admin:
    description: Use /electionadmin
    default: op
